#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine with Nginx on it.
sudo apt-get update
sudo apt-get install -y nginx
echo "#Config file for NGINX server.

server {
	listen 80 default_server;
	listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm;
}" > /etc/nginx/sites-available/default
sudo systemctl reload nginx
