#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine with Nginx on it.
apt-get update
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.html
echo "#Config file for NGINX server.

server {
	listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm;
}" > /etc/nginx/sites-available/default
service nginx reload
