#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine with Nginx on it
# and adds a /redirect_me to redirect to another page.
apt-get update
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.html
echo "#Config file for NGINX server.

server {
	listen 80 default_server;
	listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;
    }
}" > /etc/nginx/sites-available/default
service nginx reload
