#!/usr/bin/env bash
# Script that debugs a web server that was not listening on port 80.
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep nginx | head -1)"
