#!/usr/bin/env bash
# Displays: To infinity and beyond indefinitely, with a sleep 2 in between each iterationand 
# I am invincible!!! when receiving a SIGTERM signal
while :
do
    echo "To infinity and beyond"
    sleep 2
    trap "echo I am invincible!!!" 15
done
