#!/usr/bin/env bash
# Displays Holberton School 10 times with until loop.
i=0
while [ $i -lt 10 ]
do
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    echo "Holberton School"
    ((i+=1))
done
