#!/usr/bin/env bash
# Script to fix a web server to run nginx as the nginx user listening on port 8080.
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
